- name: configure router
  hosts: router
  become: yes
  roles:
    - router

- name: configure unifi controller
  hosts: unificontroller
  become: yes
  roles:
    - unificontroller

- name: configure drivemount
  hosts: drivemount
  become: yes
  roles:
    - drivemount
