- name: install ntfs
  pacman:
    name:
      - ntfs-3g 
    state: present

- name: mount drive
  ansible.posix.mount:
    src: '{{ item.src }}'
    fstype: '{{ item.fstype }}'
    path: '{{ item.path }}'
    state: present
  with_items:
    - "{{ hostvars[inventory_hostname]['mounts'] }}"
