- name: install ntfs
  pacman:
    name:
      - ntfs-3g 
    state: present

- name: create mount
  file:
    path: '{{ item.path }}'
    state: directory
    mode: '0660'
    attributes: '+i'
  with_items:
    - "{{ hostvars[inventory_hostname]['mounts'] }}"

- name: mount drive
  ansible.posix.mount:
    src: '{{ item.src }}'
    fstype: '{{ item.fstype }}'
    path: '{{ item.path }}'
    state: mounted
  with_items:
    - "{{ hostvars[inventory_hostname]['mounts'] }}"
