- name: install samba and avahi
  pacman:
    name:
      - samba
      - avahi
    state: present

- name: install samba configuration file
  copy:
    src: smb.conf
    dest: /etc/smb.conf
  notify: restart samba

- name: enable samba
  service:
    name: samba
    state: started
    enabled: yes

- name: enable avahi
  service:
    name: avahi
    state: started
    enabled: yes
