- name: install samba, avahi and wsdd
  pacman:
    name:
      - samba
      - avahi
    state: present

- name: clone wsdd from AUR
  git:
    repo: https://aur.archlinux.org/wsdd.git
    dest: /opt/aur/wsdd

- name: build wsdd
  command:
    cmd: makepkg -i
    chdir: /opt/aur/wsdd

- name: install samba configuration file
  template:
    src: smb.conf
    dest: /etc/samba/smb.conf
  notify: restart samba smb

- name: enable samba smb
  service:
    name: smb
    state: started
    enabled: yes

- name: enable avahi
  service:
    name: avahi-daemon
    state: started
    enabled: yes
