- name: set share default group acls
  ansible.posix.acl:
    path: "{{ item.0.path }}"
    entity: "{{ item.1 }}"
    etype: group
    permissions: rwX
    default: true
    state: present
  loop: "{{ hostvars[inventory_hostname]['shares'] | subelements('groups') }}"

- name: set share group acls
  ansible.posix.acl:
    path: "{{ item.0.path }}"
    entity: "{{ item.1 }}"
    etype: group
    permissions: rwX
    recursive: true
    state: present
  loop: "{{ hostvars[inventory_hostname]['shares'] | subelements('groups') }}"
