- name: set share acls
  ansible.posix.acl:
    path: "{{ item.0.path }}"
    entity: "{{ item.1 }}"
    etype: group
    permissions: rw
    default: true
    state: present
  loop: "{{ hostvars[inventory_hostname]['shares'] | subelements('groups') }}"
