- name: set share default group acls
  ansible.posix.acl:
    path: "{{ item.0.path }}"
    entity: "{{ item.1 }}"
    etype: group
    permissions: rwx
    default: true
    state: present
    recursive: true
  loop: "{{ hostvars[inventory_hostname]['shares'] | subelements('groups') }}"
