- name: set share acls
  ansible.posix.acl:
    path: /etc/foo.d/
    entity: "{{ item }}"
    etype: group
    permissions: rw
    default: true
    state: present
    with_items:
    - "{{ hostvars[inventory_hostname]['shares'] | map(attribute='groups') }}"
