- name: clone wsdd from AUR
  git:
    repo: https://aur.archlinux.org/wsdd.git
    dest: /opt/aur/wsdd
  become: true
  become_user: aur

- name: build wsdd
  command:
    cmd: makepkg -f
    chdir: /opt/aur/wsdd
  become: true
  become_user: aur

- name: install wsdd
  shell: pacman -U --noconfirm /opt/aur/wsdd/wsdd-*-any.pkg.tar.zst

- name: install wsdd configuration file
  template:
    src: conf.d/wsdd
    dest: /etc/conf.d/wsdd
  notify: restart wsdd

- name: enable wsdd
  service:
    name: wsdd
    state: started
    enabled: yes
