- name: clone wsdd from AUR
  git:
    repo: https://aur.archlinux.org/wsdd.git
    dest: /opt/aur/wsdd
  become: true
  become_user: aur

- name: build and install wsdd
  command:
    cmd: makepkg -i
    chdir: /opt/aur/wsdd
  become: true
  become_user: aur

- name: install wsdd
  pacman:
    name:
      - /opt/aur/wsdd/wsdd-*-any.pkg.tar.zst
    state: present