fileshare:
  hosts:
    localhost:
      ansible_connection: local
      mounts:
        - src: UUID=6F038B354AAEEE36
          fstype: ext4
          path: /share/newman
      shares:
        - name: newman
          users: []
          groups:
            - newman
          path: /share/newman
