fileshare:
  hosts:
    localhost:
      ansible_connection: local
      mounts:
        - src: UUID=9ddce8c5-fcc3-4cb7-98f1-78a014f7845c
          fstype: ext4
          path: /share/newman
      shares:
        - name: newman
          users: []
          groups:
            - newman
          path: /share/newman
