fileshare:
  hosts:
    localhost:
      ansible_connection: local
      mounts:
        - src: UUID=568aed03-74c3-4cc8-958f-04383f54e699
          fstype: ext4
          path: /share/newman
      shares:
        - name: newman
          users: []
          groups:
            - newman
          path: /share/newman
