- name: restart systemd-networkd
  service:
    name: systemd-networkd
    state: restarted

- name: restart nftables
  service:
    name: nftables
    state: restarted

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
