- name: install docker
  pacman:
    name: "{{ packages }}"
    state: present
  notify: restart docker
  vars:
    packages:
    - docker
    - docker-compose

- name: install docker prune service
  copy:
    src: docker-prune.service
    dest: /etc/systemd/system/docker-prune.service
  notify: restart docker prune timer

- name: install docker prune timer
  copy:
    src: docker-prune.timer
    dest: /etc/systemd/system/docker-prune.timer
  notify: restart docker prune timer

- name: enable docker prune timer
  service:
    name: docker-prune.timer
    enabled: yes
  notify: restart docker prune timer

- name: create unifi controller directory
  file:
    path: /opt/unifi-controller
    state: directory

- name: install unifi controller service
  copy:
    src: unifi-controller.service
    dest: /etc/systemd/system/unifi-controller.service
  notify: restart unifi controller

- name: enable unifi controller service
  service:
    name: unifi-controller
    enabled: yes
  notify: restart unifi controller

- name: install unifi controller docker compose file
  copy:
    src: unifi-docker-compose.yaml
    dest: /opt/unifi-controller/docker-compose.yaml
  notify: restart unifi controller
