- name: install docker
  pacman:
    name: docker
    state: present
  notify: restart docker

- name: create unifi controller directory
  file:
    path: /opt/unifi-controller
    state: directory

- name: install unifi controller service
  copy:
    src: unifi-controller.service
    dest: /etc/systemd/system/unifi-controller.service
  notify: restart unifi controller

- name: enable unifi controller service
  service:
    name: unifi-controller
    enabled: yes
  notify: restart unifi controller

- name: install unifi controller docker compose file
  copy:
    src: unifi-docker-compose.yaml
    dest: /opt/unifi-controller/docker-compose.yaml
  notify: restart unifi controller
