- name: create mongodb directory
  file:
    path: /opt/mongodb
    state: directory

- name: download and extract mongodb
  unarchive:
    src: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-4.4.2.tgz
    dest: /opt/mongodb
    remote_src: yes
  notify: restart unifi controller

- name: download and extract unifi controller
  unarchive:
    src:
    dest: /opt/unifi
    remote_src: yes
  notify: restart unifi controller

- name: install unifi controller service
  copy:
    src: unifi-controller.service
    dest: /etc/systemd/system/unifi-controller.service
  notify: restart unifi controller

- name: enable unifi controller service
  service:
    name: unifi-controller
    enabled: yes
  notify: restart unifi controller
