- name: create mongodb directory
  file:
    path: /opt/mongodb
    state: directory

- name: download and extract mongodb
  unarchive:
    src: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-4.4.2.tgz
    dest: /opt/mongodb
    remote_src: yes
    extra_opts: [--strip-components=1]
  notify: restart unifi controller

- name: install openjdk
  pacman:
    name: jre-openjdk-headless
    state: present
  notify: restart unifi controller

- name: create unifi controller directory
  file:
    path: /opt/mongodb
    state: directory

- name: install unzip
  pacman:
    name: unzip
    state: present

- name: download and extract unifi controller
  unarchive:
    src: https://dl.ui.com/unifi/6.0.41/UniFi.unix.zip
    dest: /opt/unifi
    remote_src: yes
  notify: restart unifi controller

- name: install unifi controller service
  copy:
    src: unifi-controller.service
    dest: /etc/systemd/system/unifi.service
  notify: restart unifi controller

- name: enable unifi controller service
  service:
    name: unifi
    enabled: yes
  notify: restart unifi controller
