- name: mask systemd interface naming
  file:
    src: /dev/null
    dest: /etc/systemd/network/99-default.link
    state: link
  notify: restart systemd-networkd

- name: enable systemd-networkd
  service:
    name: systemd-networkd
    enabled: yes
  notify: restart systemd-networkd

- name: create wan network
  copy:
    src: wan.network
    dest: /etc/systemd/network/wan.network
  notify: restart systemd-networkd

- name: create lan interface
  copy:
    src: lan.netdev
    dest: /etc/systemd/network/lan.netdev
  notify: restart systemd-networkd

- name: create lan network
  copy:
    src: lan.network
    dest: /etc/systemd/network/lan.network
  notify: restart systemd-networkd

- name: install nftables
  pacman:
    name: nftables
    state: present
  notify: restart nftables

- name: enable nftables service
  service:
    name: nftables
    enabled: yes
  notify: restart nftables

- name: install nftables configuration file
  copy:
    src: nftables.conf
    dest: /etc/nftables.conf
  notify: restart nftables
