- name: mask systemd interface naming
  file:
    src: /dev/null
    dest: /etc/systemd/network/99-default.link
    state: link
  notify: restart systemd-networkd

- name: enable systemd-networkd
  service:
    name: systemd-networkd
    enabled: yes
  notify: restart systemd-networkd

- name: create br0 interface
  copy:
    src: br0.netdev
    dest: /etc/systemd/network/br0.netdev
  notify: restart systemd-networkd

- name: create br0 network
  copy:
    src: br0.network
    dest: /etc/systemd/network/br0.network
  notify: restart systemd-networkd

- name: create eth0 network
  copy:
    src: eth0.network
    dest: /etc/systemd/network/eth0.network
  notify: restart systemd-networkd

- name: create eth network
  copy:
    src: eth.network
    dest: /etc/systemd/network/eth.network
  notify: restart systemd-networkd

- name: install nftables
  pacman:
    name: nftables
    state: present
  notify: restart nftables

- name: enable nftables service
  service:
    name: nftables
    enabled: yes
  notify: restart nftables

- name: install nftables configuration file
  copy:
    src: nftables.conf
    dest: /etc/nftables.conf
  notify: restart nftables

- name: create nftables directory
  file:
    path: /etc/nftables.d
    state: directory
  notify: restart nftables

- name: install dnsmasq
  pacman:
    name: dnsmasq
    state: present
  notify: restart dnsmasq

- name: enable dnsmasq
  service:
    name: dnsmasq
    enabled: yes
  notify: restart dnsmasq

- name: install dnsmasq configuration file
  copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
  notify: restart dnsmasq

- name: create dnsmasq directory
  file:
    path: /etc/dnsmasq.d
    state: directory
  notify: restart dnsmasq

- name: install resolv configuration file
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
  notify: restart dnsmasq

- name: disable systemd-resolved
  service:
    name: systemd-resolved
    enabled: no
    state: stopped
  notify: restart dnsmasq
