- include_tasks: tasks/polkit.yml
- include_tasks: tasks/systemd-networkd.yml
- include_tasks: tasks/nftables.yml
- include_tasks: tasks/systemd-networkd.yml
- include_tasks: tasks/dnsmasq.yml
- include_tasks: tasks/ssh.yml
