- name: mask systemd interface naming
  file:
    src: /dev/null
    dest: /etc/systemd/network/99-default.link
    state: link
  notify: restart systemd-networkd

- name: enable systemd-networkd
  service:
    name: systemd-networkd
    enabled: yes
  notify: restart systemd-networkd

- name: create br0 interface
  copy:
    src: systemd-networkd/br0.netdev
    dest: /etc/systemd/network/br0.netdev
  notify: restart systemd-networkd

- name: create vlan interfaces
  copy:
    src: "systemd-networkd/vlan{{ item }}.netdev"
    dest: "/etc/systemd/network/vlan{{ item }}.netdev"
  with_items:
    - 100
    - 200
  notify: restart systemd-networkd


- name: create br0 network
  copy:
    src: systemd-networkd/br0.network
    dest: /etc/systemd/network/br0.network
  notify: restart systemd-networkd

- name: create eth0 network
  copy:
    src: systemd-networkd/eth0.network
    dest: /etc/systemd/network/eth0.network
  notify: restart systemd-networkd

- name: create eth network
  copy:
    src: systemd-networkd/eth.network
    dest: /etc/systemd/network/eth.network
  notify: restart systemd-networkd
