- name: install vpp apt key
  apt_key:
    url: https://packagecloud.io/fdio/release/gpgkey
    state: present

- name: install vpp apt repository
  apt_repository:
    repo: deb https://packagecloud.io/fdio/release/ubuntu {{ ansible_lsb.codename | lower }} main
    state: present

- name: install vpp
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - vpp
    - vpp-plugin-core
    - vpp-plugin-dpdk
    - python3-vpp-api

- name: create vpp log directory
  file:
    path: /var/log/vpp
    state: directory
    owner: vpp
    group: vpp

- name: enable vpp service
  service:
    name: vpp
    state: started
    enabled: yes

- name: create fact directory
  file:
    path: /etc/ansible/facts.d/
    state: directory

- name: install vpp fact
  copy:
    src: vpp.fact
    dest: /etc/ansible/facts.d/vpp.fact
    mode: '0755'

- name: reload facts
  setup: ~

- name: configure vpp startup
  copy:
    src: startup.conf
    dest: /etc/vpp/startup.conf

- name: configure vpp router
  template:
    src: router.conf.j2
    dest: /etc/vpp/router.conf
