- name: install vpp apt key
  apt_key:
    url: https://packagecloud.io/fdio/release/gpgkey
    state: present

- name: install vpp apt repository
  apt_repository:
    repo: deb https://packagecloud.io/fdio/release/ubuntu {{ ansible_lsb.codename | lower }} main
    state: present

- name: install vpp
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - vpp
    - vpp-plugin-core
    - vpp-plugin-dpdk
    - python3-vpp-api

- name: enable vpp service
  service:
    name: vpp
    state: started
    enabled: yes
