- name: install ntfs
  pacman:
    name:
      - ntfs-3g 
    state: present

- name: create drive mount directory
  file:
    path: '{{ item.path }}'
    state: directory
    mode: '0660'
  with_items:
    - "{{ hostvars[inventory_hostname]['mounts'] }}"

- name: make drive mount directory immutable when unmounted
  shell: 'mountpoint -q {{ item.path }} || chattr +i {{ item.path }}'
  with_items:
    - "{{ hostvars[inventory_hostname]['mounts'] }}"

- name: mount drive
  ansible.posix.mount:
    src: '{{ item.src }}'
    fstype: '{{ item.fstype }}'
    path: '{{ item.path }}'
    opts: 'nofail,acl'
    state: mounted
  with_items:
    - "{{ hostvars[inventory_hostname]['mounts'] }}"
